name: ci

on:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Generate matrix
        id: generate
        uses: docker/bake-action/subaction/matrix@v6
        #with:
        #  target: default

#  validate:
#    runs-on: ubuntu-latest
#    needs:
#      - prepare
#    strategy:
#      fail-fast: false
#      matrix:
#        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
#    steps:
#      -
#        name: Validate
#        uses: docker/bake-action@v6
#        with:
#          targets: ${{ matrix.target }}

  bake:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml
      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          targets: ${{ matrix.target }}
        #  set: |
        #    *.tags=user/app:latest
