name: ci

on:
  push:
  schedule:
  - cron: "15 10 * * *"


jobs:
  #prepare:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    matrix: ${{ steps.generate.outputs.matrix }}
  #  steps:
  #    -
  #      name: Checkout
  #      uses: actions/checkout@v4
  #    -
  #      name: Generate matrix
  #      id: generate
  #      uses: docker/bake-action/subaction/matrix@v6
  #      #with:
  #      #  target: default

  bake:
    runs-on: ubuntu-latest
    #needs:
    #  - prepare
    strategy:
      fail-fast: false
      #matrix:
      #  include: ${{ fromJson(needs.prepare.outputs.matrix) }}
      matrix:
        kubectl_version:
        - "1-30"
        - "1-31"
        - "1-32"
        - "1-33"
        - "1-34"
        - "1-35"
        debian_version:
        - "11"
        - "12"
        - "13"
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml
      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          targets: "kubectl-deb${{ matrix.debian_version }}-*-${{ matrix.kubectl_version }}-*"
          #targets: ${{ matrix.target }}
        #  set: |
        #    *.tags=user/app:latest
